import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import MainNav from "@/components/MainNav/MainNav";
import {Container} from "react-bootstrap";

// Amplify.configure(outputs);

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	                                   children,
                                   }: Readonly<{
	children: React.ReactNode;
}>) {
	return (
			<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable}`}>
			<MainNav/>
			<main className="my-5">
				<Container>
					{children}
				</Container>
			</main>
			</body>
			</html>
	);
}
